#!/bin/sh

### BEGIN INIT INFO
# Provides:        plexmediaserver
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 6
# Short-Description: Start plexmediaserver 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

NAME=plexmediaserver
DAEMON=/usr/sbin/start_pms
PIDFILE=/var/run/plexmediaserver.pid

#don't run if it doesn't exist
test -x $DAEMON || exit 0

LOCKFILE=/run/lock/plexmediaserver

main() {
case $1 in
	start)
		log_daemon_msg "Starting plexmediaserver" 
		
		(
			flock -w 180 9
			start-stop-daemon --start --chuid plex:plex --exec $DAEMON &
		) 9>$LOCKFILE
		log_end_msg $?
  		;;
	stop)
		log_daemon_msg "Stopping plexmediaserver"
		pkill Plex
		log_end_msg $?
  		;;
    *)
		echo "Usage: $0 {start|stop}"
		exit 2
		;;
esac
}

main "$@"

exit 0
