#! /bin/sh
# postinst script for plex-sysvinit-compat
#

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.


case "$1" in
  
    abort-upgrade|abort-remove|abort-deconfigure|configure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# update sysVinit symlinks and start daemon
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/plexmediaserver" ]; then
		#update permissions
		if [ -d /var/lib/plexmediaserver ]; then
			chown -R plex:plex /var/lib/plexmediaserver/
		else
			mkdir -p /var/lib/plexmediaserver
			chown -R plex:plex /var/lib/plexmediaserver/
		fi
        echo "updating symlinks"
		update-rc.d plexmediaserver defaults >/dev/null
		
		# start daemon
		echo "starting plexmediaserver"
		/etc/init.d/plexmediaserver start || exit $?
	fi
fi

exit 0

